name: Docker-Build-and-Analyze

on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight UTC
  workflow_dispatch:
    inputs:
      trigger-build:
        description: 'Trigger a manual build and push'
        default: 'true'

env:
  DOCKER_IMAGE: dselen/wgdashboard:latest

jobs:
  build_analyze_push:
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: dselen/wgdashboard:latest
          outputs: type=docker,dest=/tmp/WGDashboard.tar

      - name: Install Docker Scout
        run: |
          echo "Installing Docker Scout..."
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s --
          echo "Docker Scout installed successfully."

      - name: Analyze Docker image with Docker Scout
        id: analyze-image
        run: |
          echo "Analyzing Docker image with Docker Scout..."
          docker scout cves ${{ env.DOCKER_IMAGE }} > scout-results.txt
          cat scout-results.txt
          echo "Docker Scout analysis completed."

      - name: Fail if critical CVEs are found
        run: |
          if grep -q "CRITICAL" scout-results.txt; then
            echo "Critical vulnerabilities found! Failing the job."
            exit 1
          fi

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ env.DOCKER_IMAGE }}
